name: koc_council_website
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.35.6

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  table_calendar: ^3.2.0
  english_words: ^4.0.0
  provider: 6.1.5
  firebase_core: ^4.2.1
  carousel_slider: ^5.1.0
  url_launcher: ^6.1.7
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/